use std::fmt::Write;

use crate::{analysis::Analysis, backend::Backend, error::Error, ir::*};

pub struct RustBackend;

impl RustBackend {
    pub fn new() -> Self {
        Self
    }
}

impl Backend for RustBackend {
    type Output = String;

    fn generate(&self, grammar: &GrammarIr, _analysis: &Analysis) -> Result<String, Error> {
        let mut out = String::new();

        emit_header(&mut out);

        emit_token_type(&mut out, grammar);
        emit_lexer(&mut out, grammar)?;
        emit_parser(&mut out, grammar)?;

        Ok(out)
    }
}

fn emit_header(out: &mut String) {
    writeln!(
        out,
        r#"// Generated by ebnf.
// DO NOT EDIT.

use regex::Regex;

#[derive(Debug, Clone)]
pub struct Span {{
    pub start: usize,
    pub end: usize,
}}

#[derive(Debug, Clone)]
pub struct Token {{
    pub kind: TokenKind,
    pub lexeme: String,
    pub span: Span,
}}
"#
    )
    .unwrap();
}

fn emit_token_type(out: &mut String, grammar: &GrammarIr) {
    writeln!(out, "#[derive(Debug, Clone, PartialEq, Eq)]").unwrap();
    writeln!(out, "pub enum TokenKind {{").unwrap();

    for token in &grammar.tokens {
        if !token.skip {
            writeln!(out, "    {},", token.name).unwrap();
        }
    }

    // Literals become generated token variants.
    let mut literals = Vec::new();

    for rule in &grammar.rules {
        for alt in &rule.alternatives {
            for symbol in &alt.symbols {
                if let SymbolIr::Terminal(value) = symbol {
                    if !literals.contains(value) {
                        literals.push(value.clone());
                    }
                }
            }
        }
    }

    for literal in literals {
        writeln!(out, "    {},", literal_variant(&literal)).unwrap();
    }

    writeln!(out, "    Eof,").unwrap();
    writeln!(out, "}}\n").unwrap();
}

fn emit_lexer(out: &mut String, grammar: &GrammarIr) -> Result<(), Error> {
    writeln!(
        out,
        r#"pub struct Lexer {{
    rules: Vec<(Regex, TokenKind, bool)>,
}}

impl Lexer {{
    pub fn new() -> Result<Self, regex::Error> {{
        let mut rules = Vec::new();
"#
    )
    .unwrap();

    for token in &grammar.tokens {
        let kind = token_variant(&token.name);

        writeln!(
            out,
            "        rules.push((Regex::new(r#\"^(?:{})\"#)?, TokenKind::{}, {}));",
            token.pattern, kind, token.skip
        )
        .unwrap();
    }

    writeln!(
        out,
        r#"        Ok(Self {{ rules }})
    }}

    pub fn tokenize(&self, input: &str) -> Result<Vec<Token>, String> {{
        let mut result = Vec::new();
        let mut pos = 0;

        while pos < input.len() {{
            let rest = &input[pos..];
            let mut matched = false;

            for (regex, kind, skip) in &self.rules {{
                if let Some(m) = regex.find(rest) {{
                    if m.start() != 0 {{
                        continue;
                    }}

                    let text = m.as_str();

                    if text.is_empty() {{
                        return Err(format!(
                            "lexer rule matched empty input at {{}}",
                            pos
                        ));
                    }}

                    let end = pos + text.len();

                    if !*skip {{
                        result.push(Token {{
                            kind: kind.clone(),
                            lexeme: text.to_string(),
                            span: Span {{
                                start: pos,
                                end,
                            }},
                        }});
                    }}

                    pos = end;
                    matched = true;
                    break;
                }}
            }}

            if !matched {{
                return Err(format!(
                    "unexpected character at byte {{}}",
                    pos
                ));
            }}
        }}

        result.push(Token {{
            kind: TokenKind::Eof,
            lexeme: String::new(),
            span: Span {{
                start: pos,
                end: pos,
            }},
        }});

        Ok(result)
    }}
}}
"#
    )
    .unwrap();

    Ok(())
}

fn emit_parser(out: &mut String, grammar: &GrammarIr) -> Result<(), Error> {
    writeln!(
        out,
        r#"#[derive(Debug)]
pub struct Parser {{
    tokens: Vec<Token>,
    pos: usize,
}}

impl Parser {{
    pub fn new(tokens: Vec<Token>) -> Self {{
        Self {{ tokens, pos: 0 }}
    }}

    fn peek(&self) -> &Token {{
        &self.tokens[self.pos]
    }}

    fn advance(&mut self) -> Token {{
        let token = self.tokens[self.pos].clone();
        self.pos += 1;
        token
    }}

    fn expect(&mut self, kind: TokenKind) -> Result<Token, String> {{
        if self.peek().kind == kind {{
            Ok(self.advance())
        }} else {{
            Err(format!(
                "expected {{:?}}, got {{:?}}",
                kind,
                self.peek().kind
            ))
        }}
    }}
"#
    )
    .unwrap();

    for rule in &grammar.rules {
        emit_rule(out, rule)?;
    }

    writeln!(out, "}}\n").unwrap();

    Ok(())
}

fn emit_rule(out: &mut String, rule: &RuleIr) -> Result<(), Error> {
    writeln!(
        out,
        "    pub fn parse_{}(&mut self) -> Result<(), String> {{",
        rule.name
    )
    .unwrap();

    if rule.alternatives.len() == 1 {
        emit_alternative(out, &rule.alternatives[0])?;
    } else {
        writeln!(out, "        match &self.peek().kind {{").unwrap();

        for alt in &rule.alternatives {
            if let Some(first) = alt.symbols.first() {
                writeln!(out, "            {} => {{", match_pattern(first)).unwrap();

                emit_alternative_body(out, alt)?;

                writeln!(out, "            }}").unwrap();
            }
        }

        writeln!(
            out,
            "            _ => return Err(format!(\"unexpected token: {{:?}}\", self.peek().kind)),"
        )
        .unwrap();

        writeln!(out, "        }}").unwrap();
    }

    writeln!(out, "        Ok(())").unwrap();
    writeln!(out, "    }}\n").unwrap();

    Ok(())
}

fn emit_alternative(out: &mut String, alt: &AlternativeIr) -> Result<(), Error> {
    emit_alternative_body(out, alt)
}

fn emit_alternative_body(out: &mut String, alt: &AlternativeIr) -> Result<(), Error> {
    for symbol in &alt.symbols {
        match symbol {
            SymbolIr::Terminal(value) => {
                writeln!(
                    out,
                    "                self.expect(TokenKind::{})?;",
                    literal_variant(value)
                )
                .unwrap();
            }

            SymbolIr::Token(name) => {
                writeln!(
                    out,
                    "                self.expect(TokenKind::{})?;",
                    token_variant(name)
                )
                .unwrap();
            }

            SymbolIr::Rule(name) => {
                writeln!(out, "                self.parse_{}()?;", name).unwrap();
            }
        }
    }

    Ok(())
}

fn match_pattern(symbol: &SymbolIr) -> String {
    match symbol {
        SymbolIr::Terminal(value) => {
            format!("TokenKind::{}", literal_variant(value))
        }

        SymbolIr::Token(name) => {
            format!("TokenKind::{}", token_variant(name))
        }

        SymbolIr::Rule(name) => {
            // This is simplistic. A production backend should use
            // FIRST sets here.
            format!("_ /* FIRST({}) */", name)
        }
    }
}

fn token_variant(name: &str) -> String {
    name.to_string()
}

fn literal_variant(value: &str) -> String {
    let mut result = String::from("Lit_");

    for c in value.chars() {
        if c.is_ascii_alphanumeric() {
            result.push(c);
        } else {
            result.push_str(&format!("U{:04X}", c as u32));
        }
    }

    result
}
